Traceback (most recent call last):
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 242, in process
    return self.handle()
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 415, in _delegate
    return handle_class(cls)
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 390, in handle_class
    return tocall(*args)
  File "webinterface.py", line 77, in POST
    game.update_local_knowledgebase(question_id, answer)
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/twentyquestions.py", line 106, in update_local_knowledgebase
    objects_values[weight.object_id] += answer*weight.value
KeyError: 1

Traceback (most recent call last):
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 242, in process
    return self.handle()
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 415, in _delegate
    return handle_class(cls)
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/web/application.py", line 390, in handle_class
    return tocall(*args)
  File "webinterface.py", line 78, in POST
    game.update_local_knowledgebase(question_id, answer)
  File "/home/andy/school/cs321_AI/work_with_dan/20questions/twentyquestions.py", line 106, in update_local_knowledgebase
    for weight in weights:
KeyError: 1

98.228.181.68:47083 - - [22/May/2010 19:16:22] "HTTP/1.1 POST /answer/11" - 500 Internal Server Error

